### PR TITLE
Tidy up some cmake files

### PR DESCRIPTION
**Pull request by dtebbs**
Addresses #46

### CODE REVIEW

**Comment by AntoineRondelet** [comment]
Let's look at #50 first and merge this one after the resolution of the problem with `test_prover` and `libboost`.

**Comment by dtebbs** [comment]
> Let's look at #50 first and merge this one after the resolution of the problem with test_prover and libboost.

Yes.  Sorry about that.  For some reason, I didn't need to link boost_system on my machine (mac difference, maybe), so I didn't include it.
I pushed a slightly different way of specifying the boost_system dependency, but feel free to force-push or replace with your PR if you prefer.

**Comment by AntoineRondelet** [comment]
> I pushed a slightly different way of specifying the boost_system dependency, but feel free to force-push or replace with your PR if you prefer.

Have you pushed on this branch? I can't see any new commits to link `boost_system`

**Comment by dtebbs** [comment]
Sorry, the push didn't work.  Should be there now.

**Pull request merged**
