### PR TITLE
Fix prover_server --keypair flag

### PR DESCRIPTION
**Pull request by dtebbs**
Addresses #260

### CODE REVIEW

**Comment by AntoineRondelet** [comment]
The `build-macos (Debug) (push)` is often failing because MPC contributors timeout in the mpc tests.. That's something that would need refinement in the future. I'll re-run the jobs just for the sake of merging a PR that is fully validated by the CI, and merge afterwards as it LGTM

**Comment by AntoineRondelet** [comment]
Re-running a single job isn't yet possible on Github actions apparently: https://github.community/t/ability-to-rerun-just-a-single-job-in-a-workflow/17234/39
This is a pain...

**Review by AntoineRondelet — APPROVED** [review]
LGTM

**Comment by dtebbs** [comment]
> The `build-macos (Debug) (push)` is often failing because MPC contributors timeout in the mpc tests.. That's something that would need refinement in the future. I'll re-run the jobs just for the sake of merging a PR that is fully validated by the CI, and merge afterwards as it LGTM

Yes, I've seen a few mysterious failures too, which may be the same thing.  I created #262 to keep track of this.  I couldn't find a link to a github action showing the failure (I guess re-running removes the logs from the previous run), so we might want to copy-paste a few lines in that issue.

**Comment by AntoineRondelet** [comment]
> > The `build-macos (Debug) (push)` is often failing because MPC contributors timeout in the mpc tests.. That's something that would need refinement in the future. I'll re-run the jobs just for the sake of merging a PR that is fully validated by the CI, and merge afterwards as it LGTM
> 
> @AntoineRondelet Yes, I've seen a few mysterious failures too, which may be the same thing. I created #262 to keep track of this. I couldn't find a link to a github action showing the failure (I guess re-running removes the logs from the previous run), so we might want to copy-paste a few lines in that issue if we notice it again.

Oh indeed, the logs are overwritten when we restart the jobs. Yes definitely, let's copy the logs of this failing job next time before restarting in order to paste them to the ticket you opened.

**Pull request merged**
