### PR TITLE
Update libsnark [add-pairing-gadgets]

### PR DESCRIPTION
**Pull request by dtebbs**
Depends on:
- [x] clearmatics/libsnark#25
- [x] clearmatics/libsnark#26
- [x] clearmatics/libsnark#29

### CODE REVIEW

**Comment by dtebbs** [comment]
#413 contains the fix for the codeql job

**Review by AntoineRondelet — APPROVED** [review]
LGTM once rebased on top of `origin/develop` which now contains the changes from #413

**Comment by dtebbs** [comment]
Updated to point to clearmatics/libsnark#407 and rebased.

**Comment by AntoineRondelet** [comment]
> Updated to point to clearmatics/libsnark#407 and rebased.

clearmatics/libsnark#407?

**Pull request merged**
